### ISSUE TITLE
Tooltip React Component

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/react-components#50]
**Requirements:**

- [x] Should match the style shown in [specks](https://drive.google.com/drive/u/0/folders/0B1LbmKnex41fMkVfWFhSUlR3eGM)
- [x] The tooltip should be flexible and detect the position of the target relative to the viewport edge. By default the preferred orientation of the tooltip is above the target, centered. If this is not possible, the tooltip should try to stay above the target and the tooltip pointer should align with the center of the target. It should follow top, right, bottom, left as order of precedence when it is not possible to render it at particular placement, move to the next.
- [x] Tooltips should be at least 10px (should be configurable) from the viewport edge. The tooltip pointer should be 5px (should be configurable) from the target.
- [x] Use a css-only solution for the tooltip pointer: square that is rotated 45º and aligns with the background. This way you can position it centered to the target, and use drop-shadow if needed for the whole thing.
- [x] Should allow any content (e.g. any other React component) inside the tooltip
- [x] Tooltip trigger should be configurable. For now, we need click and hover as two possible triggers
- [x] Delay (in milliseconds) in rendering the tooltip, on the configured trigger, should also be configurable
- [x] Should support themes. For now we would have only single theme, default.
- [x] Should support adding custom css class to the root container of the tooltip

**Comment by Colinh84** [comment]
working on this.

**Comment by vikasrohit** [comment]
:+1: Go ahead

**Comment by vikasrohit** [comment]
@Colinh84 Please let us know here if you have any query.

**Comment by Colinh84** [comment]
@vikasrohit I initially had some problems as the base repo doesn't build without errors on my Windows dev system, but I have it running now on my linux system and should have this task completed soon.

**Comment by vikasrohit** [comment]
Thanks @Colinh84 for the update.

**Comment by nlitwin** [comment]
Let us know if the error is with our repo. We definitely want the repo to be runnable on Windows too :)

**Comment by amolskh** [comment]
Even I faced this issue that repo dosent work on windows gets deployed without errors by when I open url in browser get several errors

**Comment by Colinh84** [comment]
@nlitwin It seems to be an error caused by some incompatible node modules in the repo, here is the error and stack trace that happens when I run "npm run dev":

ERROR in ./~/react-dropzone/lib/index.js
Module build failed: ReferenceError: [BABEL] C:\Users\colin_000\Documents\dev\react-components\node_modules\react-dropzone\lib\index.js: Using removed Babel 5 option: C:\Users\colin_000\Documents\dev\react-components\node_modules\react-dropzone\.babelrc.stage - Check out the corresponding stage-x presets http://babeljs.io/docs/plugins/#presets
  at Logger.error (C:\Users\colin_000\Documents\dev\react-components\node_modules\babel-core\lib\transformation\file\logger.js:39:11)
  at OptionManager.mergeOptions (C:\Users\colin_000\Documents\dev\react-components\node_modules\babel-core\lib\transformation\file\options\option-manager.js:265:20)
  at OptionManager.addConfig (C:\Users\colin_000\Documents\dev\react-components\node_modules\babel-core\lib\transformation\file\options\option-manager.js:207:10)
  at OptionManager.findConfigs (C:\Users\colin_000\Documents\dev\react-components\node_modules\babel-core\lib\transformation\file\options\option-manager.js:413:16)
  at OptionManager.init (C:\Users\colin_000\Documents\dev\react-components\node_modules\babel-core\lib\transformation\file\options\option-manager.js:461:12)
  at File.initOptions (C:\Users\colin_000\Documents\dev\react-components\node_modules\babel-core\lib\transformation\file\index.js:194:75)
  at new File (C:\Users\colin_000\Documents\dev\react-components\node_modules\babel-core\lib\transformation\file\index.js:123:22)
  at Pipeline.transform (C:\Users\colin_000\Documents\dev\react-components\node_modules\babel-core\lib\transformation\pipeline.js:45:16)
  at transpile (C:\Users\colin_000\Documents\dev\react-components\node_modules\babel-loader\index.js:14:22)
  at Object.module.exports (C:\Users\colin_000\Documents\dev\react-components\node_modules\babel-loader\index.js:88:12)
 @ ./components/FileUploader/FileUploader.cjsx 11:11-36

ERROR in ./~/redux-thunk/lib/index.js
Module build failed: ReferenceError: [BABEL] C:\Users\colin_000\Documents\dev\react-components\node_modules\redux-thunk\lib\index.js: Using removed Babel 5 option: C:\Users\colin_000\Documents\dev\react-components\node_modules\redux-thunk\.babelrc.stage - Check out the corresponding stage-x presets http://babeljs.io/docs/plugins/#presets
  at Logger.error (C:\Users\colin_000\Documents\dev\react-components\node_modules\babel-core\lib\transformation\file\logger.js:39:11)
  at OptionManager.mergeOptions (C:\Users\colin_000\Documents\dev\react-components\node_modules\babel-core\lib\transformation\file\options\option-manager.js:265:20)
  at OptionManager.addConfig (C:\Users\colin_000\Documents\dev\react-components\node_modules\babel-core\lib\transformation\file\options\option-manager.js:207:10)
  at OptionManager.findConfigs (C:\Users\colin_000\Documents\dev\react-components\node_modules\babel-core\lib\transformation\file\options\option-manager.js:413:16)
  at OptionManager.init (C:\Users\colin_000\Documents\dev\react-components\node_modules\babel-core\lib\transformation\file\options\option-manager.js:461:12)
  at File.initOptions (C:\Users\colin_000\Documents\dev\react-components\node_modules\babel-core\lib\transformation\file\index.js:194:75)
  at new File (C:\Users\colin_000\Documents\dev\react-components\node_modules\babel-core\lib\transformation\file\index.js:123:22)
  at Pipeline.transform (C:\Users\colin_000\Documents\dev\react-components\node_modules\babel-core\lib\transformation\pipeline.js:45:16)
  at transpile (C:\Users\colin_000\Documents\dev\react-components\node_modules\babel-loader\index.js:14:22)
  at Object.module.exports (C:\Users\colin_000\Documents\dev\react-components\node_modules\babel-loader\index.js:88:12)
 @ ./~/appirio-tech-client-app-layer/src/store/configureStore.js 10:18-40

**Comment by nlitwin** [comment]
Thank you! I will try to run it on my Windows partition tonight and see if I can get it working

**Comment by vikasrohit** [comment]
@Colinh84 Submission is closing. Are you able to complete the task?

**Comment by amolskh** [comment]
If allowed I can try to this one up

**Comment by vikasrohit** [comment]
@amolskh we need to wait for @Colinh84's confirmation before releasing it. And in any case we have very few minutes remaining to the submission end time.

**Comment by vikasrohit** [comment]
@Colinh84 We have extended the submission timeline by 24 hours to allow you to complete the task. Please let us know if you would not be able to do so.

**Comment by Colinh84** [comment]
@vikasrohit very close to submitting, just creating some extra examples for testing now.

**Comment by vikasrohit** [comment]
Awesome. Please make sure you submit the PR before submission end time which is less than 7 hours from now. Also, please submit a zip with a text file mentioning the tickets you have worked on for this challenge.

**Comment by Colinh84** [comment]
@vikasrohit Alright, got the pull request in: https://github.com/appirio-tech/react-components/pull/72
Note that I created the merge request to master as instructed in the challenge details, but there are whole bunch of other commits mixed up in the PR since I started working from the dev branch as was requested in the forums..

**Comment by vikasrohit** [comment]
@Colinh84 I have synced dev branch with master last week and starting this week. So, even if you take pull from origin/dev, it should remove conflicts and number of changes in your PR.

**Comment by Colinh84** [comment]
Updated PR: https://github.com/appirio-tech/react-components/pull/73

**Comment by vikasrohit** [comment]
@Colinh84 
Final fix items:

- [ ] Move example theme (.blue-round) styling to example scss
- [ ] Can we remove dependency on id of the element to show tooltip against it? One way could be wrap target element in tooltip component like `<Tooltip><div className="target"></div><div className="tootlip-body"></div></Tooltip>`

**Comment by Colinh84** [comment]
@vikasrohit Final fixes have been implemented, PR here: https://github.com/appirio-tech/react-components/pull/78
